name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --base-href "/" --dart-define=APIKEY=${{ secrets.APIKEY }} --dart-define=APPID=${{ secrets.APPID }} --dart-define=MESSAGINGSENDERID=${{ secrets.MESSAGINGSENDERID }} --dart-define=PROJECTID=${{ secrets.PROJECTID }} --dart-define=STORAGEBUCKET=${{ secrets.STORAGEBUCKET }} --dart-define=AUTHDOMAIN=${{ secrets.AUTHDOMAIN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: mysteryheroesmashup.com